version: "3.3"
services:
  caddy-gen:
    container_name: caddy-gen
    image: "wemakeservices/caddy-gen:latest"
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - caddy-certificates:/data/caddy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - plausible
      - commento

  plausible:
    labels:
      virtual.host: "t2h.app" # change to your domain name
      virtual.port: "8000"
      virtual.tls-email: "pankaj@time2hack.com" # change to your email
  commento:
    labels:
      virtual.host: "commento.t2h.app" # change to your domain name
      virtual.port: "8787"
      virtual.tls-email: "pankaj@time2hack.com" # change to your email
        
volumes:
    caddy-certificates:
        driver: local
  